apiVersion: v1
kind: Service
metadata:
  name: organisationsai-service
  labels:
    app: organisationsai
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: organisationsai
